name: Check if the gem exists on rubygems.org

on: [pull_request]

jobs:
  build-gem:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        ruby-version: ['2.5', '2.7']
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Check if gem exists
        run: |
          LOCAL_GEM_VERSION=$(ruby -e "require 'scc/codestyle'; print Scc::Codestyle::VERSION" -I lib)
          REMOTE_GEM_VERSION=$(curl 'https://rubygems.org/api/v1/versions/scc-codestyle/latest.json' | jq '.version')
          if [ "$LOCAL_GEM_VERSION" == "$REMOTE_GEM_VERSION" ]; then (echo "bump the gem version!" && exit 1); else exit 0; fi
